name: Testsuite python development version

on:
  push:
    branches:
      - master
      - develop
  schedule:
    - cron: "0 10 * * 0"

jobs:
  testsuite:
    name: Test suiite
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: svg

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.13-dev'
    - name: Install dependencies minimal
      run: |
        sudo apt-get install libopenblas-dev libhdf5-dev
        python -m pip install --upgrade pip
        pip install -U setuptools setuptools_scm wheel
        pip install -e .[unit-testing]
    - name: Unit tests minimal
      run: pytest

    - name: Install dependencies complete
      continue-on-error: true
      run: |
        pip install -e .[all,testing]
    - name: Unit tests complete
      continue-on-error: true
      run: pytest
    - name: Notebook flow tests
      uses: coactions/setup-xvfb@v1
      continue-on-error: true
      with:
        run: python -m pytest -m demos
